---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  directories:
    - node_modules
    - $HOME/.yarn-cache

before_install:
  - npm config set spin false
  - npm install -g yarn

install:
  - yarn
  - npm install phantomjs-prebuilt
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version

script:
  - npm run test:ci

env:
  - SAUCE_USERNAME=mobiledoc-kit SAUCE_ACCESS_KEY=f9cad21d-1141-452d-8f64-c6ba3f43faa6
